### ISSUE TITLE
Support "id" and "internal" for mww

### ISSUE THREAD

**Issue by flubshi** [kahrendt/microWakeWord#58]
Hi @kahrendt ,

looking at your improvements of mww in [home-assistant-voice-pe](https://github.com/esphome/home-assistant-voice-pe/tree/dev/esphome/components/micro_wake_word) I noticed that you implemented support for `id` and `internal` for mww. Example:

```yml
micro_wake_word:
  id: mww
  models:
    - model: hey_mycroft
      id: hey_mycroft
    - model: https://github.com/kahrendt/microWakeWord/releases/download/stop/stop.json
      id: stop
      internal: true
```

Since I want to experiment with the stop word feature as implemented in `home-assistant-voice-pe` I would like to ask, if you could please implement it in the upstream mww.
