### ISSUE TITLE
How to deploy the model to esp32 device?

### ISSUE THREAD

**Issue by DingPengfei** [kahrendt/microWakeWord#64]
It;'s a great tool !
But how to deploy the model file on esp32 device, can you provide more details about this?
from the [Espressif](https://www.espressif.com/zh-hans/products/socs/esp32) official, we can only provide audio data for training by them to get a support model file.

**Comment by MichaMD** [comment]
Using Esphome. and then configuring the yaml:

z.B.
```
micro_wake_word:
  models:
    - model: hey_jarvis
  microphone: va_mic
  stop_after_detection: false
  on_wake_word_detected:
    - logger.log: "🎤 Wake word triggered!"
```
